# Generated by Django 5.0.4 on 2024-05-11 16:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administrator', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cust_name', models.CharField(max_length=50, null=True)),
                ('ph_no', models.BigIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField(max_length=100, null=True)),
                ('country', models.CharField(max_length=50)),
                ('Cid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rooms_booked', models.IntegerField()),
                ('check_in', models.DateField()),
                ('check_out', models.DateField()),
                ('resort', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrator.resort')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrator.rooms')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Customerwallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_no', models.BigIntegerField()),
                ('balance', models.IntegerField()),
                ('Rid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrator.resort')),
                ('cust_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.TextField(max_length=100)),
                ('rating', models.IntegerField()),
                ('resort', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrator.resort')),
            ],
        ),
    ]
